<a href="https://colab.research.google.com/github/Priya-Kumari-Chourasia/Pytorch_tutorials/blob/main/nn_module.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

the torch nn module is a core library that provides a wide array of classes and functions designed to help developers build neural networks efficiently and effectively.

In [4]:
import torch
import torch.nn as nn

class Model(nn.Module):
  def __init__(self,num_features):
    super().__init__()

    self.linear = nn.Linear(num_features,1)
    self.sigmoid = nn.Sigmoid()

  def forward(self,features):
    out = self.linear(features)
    out= self.sigmoid(out)

    return out


In [5]:
features = torch.rand(10,5)
features

tensor([[0.9171, 0.7439, 0.1267, 0.7067, 0.1004],
        [0.1133, 0.1561, 0.8001, 0.0344, 0.0591],
        [0.3183, 0.7432, 0.1350, 0.5258, 0.6583],
        [0.8422, 0.8644, 0.7300, 0.3407, 0.6470],
        [0.5699, 0.0649, 0.7281, 0.8891, 0.5818],
        [0.6906, 0.2053, 0.4950, 0.1056, 0.0923],
        [0.6395, 0.3022, 0.4997, 0.5888, 0.2387],
        [0.8776, 0.7467, 0.6455, 0.5841, 0.2141],
        [0.2815, 0.9293, 0.9286, 0.3075, 0.1535],
        [0.2842, 0.7998, 0.1699, 0.7103, 0.9941]])

In [6]:
model = Model(features.shape[1])

model(features)

tensor([[0.3269],
        [0.4162],
        [0.3035],
        [0.2772],
        [0.4077],
        [0.3594],
        [0.3790],
        [0.3344],
        [0.3562],
        [0.2878]], grad_fn=<SigmoidBackward0>)

In [7]:
model.linear.weight

Parameter containing:
tensor([[-0.2900, -0.3700,  0.2125,  0.3368, -0.3998]], requires_grad=True)

In [9]:
model.linear.bias

Parameter containing:
tensor([-0.4058], requires_grad=True)

In [10]:
!pip install torchinfo

In [11]:
from torchinfo import summary
summary(model,input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

In [14]:
import torch
import torch.nn as nn

class Model(nn.Module):
  def __init__(self,num_features):
    super().__init__()

    self.linear1 = nn.Linear(num_features,3)
    self.relu = nn.ReLU()
    self.linear2 = nn.Linear(3,1)
    self.sigmoid = nn.Sigmoid()

  def forward(self,features):
    out = self.linear1(features)
    out= self.relu(out)
    out=self.linear2(out)
    out = self.sigmoid(out)

    return out


In [15]:
features = torch.rand(10,5)
model = Model(features.shape[1])
model(features)

tensor([[0.5860],
        [0.5662],
        [0.5865],
        [0.5526],
        [0.5691],
        [0.5684],
        [0.5427],
        [0.5925],
        [0.5849],
        [0.5709]], grad_fn=<SigmoidBackward0>)

In [16]:
from torchinfo import summary
summary(model,input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 3]                   18
├─ReLU: 1-2                              [10, 3]                   --
├─Linear: 1-3                            [10, 1]                   4
├─Sigmoid: 1-4                           [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

sequential

In [19]:
class Model(nn.Module):
  def __init__(self,num_features):
    super().__init__()
    self.network = nn.Sequential(
        nn.Linear(num_features,3),
        nn.ReLU(),
        nn.Linear(3,1),
        nn.Sigmoid()
        )
  def forward(self,features):
      out = self.network(features)
      return out

In [20]:
features = torch.rand(10,5)

model = Model(features.shape[1])
model(features)

tensor([[0.5225],
        [0.5152],
        [0.5138],
        [0.5142],
        [0.5225],
        [0.5160],
        [0.5190],
        [0.5225],
        [0.5197],
        [0.5190]], grad_fn=<SigmoidBackward0>)