<a href="https://colab.research.google.com/github/Priya-Kumari-Chourasia/Pytorch_tutorials/blob/main/tensors_in_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch
print(torch.__version__)

2.11.0+cu128


In [3]:
if torch.cuda.is_available():
  print("Gpu is available")
  print(f"Using GPU:{torch.cuda.get_device_name(0)}")
else:
  print("GPU is not available .Using CPU")

GPU is not available .Using CPU


### Creating Tensor

In [6]:
# using empty- allocation location and show the value which are already present
a=torch.empty(2,3)

In [7]:
# check type
type(a)

torch.Tensor

In [8]:
#using zeros
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [9]:
#using ones
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [10]:
#using rand
torch.rand(2,3)

tensor([[0.9692, 0.6050, 0.7278],
        [0.2215, 0.3463, 0.8873]])

In [12]:
#use of seed
torch.manual_seed(23)
torch.rand(2,3)

tensor([[0.4283, 0.2889, 0.4224],
        [0.3571, 0.9577, 0.1100]])

In [13]:
torch.manual_seed(23)
torch.rand(2,3)

tensor([[0.4283, 0.2889, 0.4224],
        [0.3571, 0.9577, 0.1100]])

In [15]:
# using tensor
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [16]:
torch.arange(0,10,2)

tensor([0, 2, 4, 6, 8])

In [17]:
torch.linspace(1,10,10)

tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [18]:
torch.eye(5)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [19]:
torch.full((3,3),5)

tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])

### Tensor Shapes

In [20]:
x = torch.tensor([[1,2,3],[4,5,6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [21]:
x.shape

torch.Size([2, 3])

In [22]:
torch.empty_like(x)

tensor([[7309453675965983778, 8315168162784306286, 8367752027310484831],
        [7954801838398993778, 2459029315949324647, 3905858043186329139]])

In [23]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [24]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [25]:
torch.rand_like(x)
# gettin error because rand generate float numbers and x contains integer data type

NotImplementedError: "check_uniform_bounds" not implemented for 'Long'

In [29]:
torch.rand_like(x,dtype=torch.float32)

tensor([[0.2933, 0.9205, 0.5876],
        [0.1299, 0.6729, 0.1028]])

### Tensor Data Types

In [26]:
x.dtype

torch.int64

In [27]:
torch.tensor([1.0,2.0,3.0,6.9],dtype=torch.int32)

tensor([1, 2, 3, 6], dtype=torch.int32)

In [28]:
x.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

### Mathematical Operations

#### Scaler operation

In [30]:
x = torch.rand(2,2)
x

tensor([[0.7876, 0.5540],
        [0.4653, 0.2311]])

In [31]:
# addition
x+2

tensor([[2.7876, 2.5540],
        [2.4653, 2.2311]])

In [32]:
# subtraction
x-2

tensor([[-1.2124, -1.4460],
        [-1.5347, -1.7689]])

In [33]:
# multiplication

x*3

tensor([[2.3629, 1.6619],
        [1.3958, 0.6932]])

In [34]:
# division
x/3

tensor([[0.2625, 0.1847],
        [0.1551, 0.0770]])

In [35]:
((x*100)//3)%2

tensor([[0., 0.],
        [1., 1.]])

In [36]:
# power
x**2

tensor([[0.6204, 0.3069],
        [0.2165, 0.0534]])

#### Element wise operation

In [37]:
a = torch.rand(2,3)
b = torch.rand(2,3)

print(a)
print(b)

tensor([[0.2214, 0.3348, 0.4541],
        [0.2519, 0.6310, 0.1707]])
tensor([[0.3122, 0.1976, 0.5466],
        [0.0213, 0.9049, 0.8444]])


In [38]:
# add
a+b

tensor([[0.5336, 0.5324, 1.0007],
        [0.2732, 1.5359, 1.0151]])

In [39]:
# subtraction
a-b

tensor([[-0.0908,  0.1372, -0.0925],
        [ 0.2307, -0.2739, -0.6738]])

In [40]:
# multiplication
a*b

tensor([[0.0691, 0.0662, 0.2482],
        [0.0054, 0.5710, 0.1441]])

In [41]:
# division
a/b

tensor([[ 0.7091,  1.6945,  0.8308],
        [11.8435,  0.6973,  0.2021]])

In [42]:
#power
a**b

tensor([[0.6245, 0.8056, 0.6495],
        [0.9711, 0.6593, 0.2247]])

In [43]:
# mod
a%b

tensor([[0.2214, 0.1372, 0.4541],
        [0.0179, 0.6310, 0.1707]])

In [44]:
c = torch.tensor([1,-2,-5,8])

In [45]:
# abs
torch.abs(c)

tensor([1, 2, 5, 8])

In [46]:
# negative
torch.neg(c)

tensor([-1,  2,  5, -8])

In [47]:
d = torch.tensor([1.8,4.5,6.7,3.5])

In [49]:
torch.round(d)

tensor([2., 4., 7., 4.])

In [50]:
torch.floor(d)

tensor([1., 4., 6., 3.])

In [51]:
torch.clamp(d,min=2,max=3)

tensor([2., 3., 3., 3.])

#### Reduction Operation

In [52]:
e = torch.randint(size=(2,3),low=0,high=10)
e

tensor([[1, 2, 4],
        [3, 3, 5]])

In [54]:
# sum
torch.sum(e)

tensor(18)

In [55]:
torch.sum(e,dim=0)

tensor([4, 5, 9])

In [56]:
torch.sum(e,dim=1)

tensor([ 7, 11])

In [58]:
f= torch.randint(size=(2,3),low=0,high=10,dtype=torch.float32)

In [62]:
f

tensor([[1., 1., 9.],
        [6., 3., 9.]])

In [59]:
# mean
torch.mean(f)

tensor(4.8333)

In [60]:
torch.mean(f,dim=0)

tensor([3.5000, 2.0000, 9.0000])

In [61]:
torch.median(f)

tensor(3.)

In [63]:
torch.max(f)
torch.min(f)

tensor(1.)

In [65]:
#product
torch.prod(f)

tensor(1458.)

In [66]:
# standard deviation
torch.std(f)

tensor(3.7103)

In [67]:
torch.var(f)

tensor(13.7667)

In [68]:
torch.argmax(f)

tensor(2)

In [69]:
torch.argmin(f)

tensor(0)

#### Matrix operation

In [71]:
f= torch.randint(size=(2,3),low=0,high=10)
g =torch.randint(size=(3,2),low=0,high=10)

In [72]:
print(f)
print(g)

tensor([[6, 1, 3],
        [4, 1, 1]])
tensor([[8, 6],
        [4, 5],
        [2, 0]])


In [73]:
torch.matmul(f,g)

tensor([[58, 41],
        [38, 29]])

In [75]:
torch.dot(f,g)

RuntimeError: 1D tensors expected, but got 2D and 2D tensors

In [74]:
# dot product
vector1 = torch.tensor([1,2])
vector2 = torch.tensor([3,4])

torch.dot(vector1,vector2)

tensor(11)

In [76]:
f

tensor([[6, 1, 3],
        [4, 1, 1]])

In [78]:
f.T

tensor([[6, 4],
        [1, 1],
        [3, 1]])

In [82]:
h = torch.randint(size=(3,3),low=0,high=10,dtype=torch.float32)
h

tensor([[2., 2., 8.],
        [8., 0., 1.],
        [0., 3., 2.]])

In [83]:
torch.det(h)

tensor(154.)

In [84]:
torch.inverse(h)

tensor([[-0.0195,  0.1299,  0.0130],
        [-0.1039,  0.0260,  0.4026],
        [ 0.1558, -0.0390, -0.1039]])

#### comparison operations

In [85]:
i = torch.randint(size=(2,3),low=0,high=10)
j = torch.randint(size=(2,3),low=0,high=10)

print(i)
print(j)

tensor([[8, 0, 4],
        [1, 1, 5]])
tensor([[2, 5, 4],
        [7, 8, 3]])


In [86]:
i>j

tensor([[ True, False, False],
        [False, False,  True]])

In [87]:
i==j

tensor([[False, False,  True],
        [False, False, False]])

In [88]:
i<j

tensor([[False,  True, False],
        [ True,  True, False]])

In [89]:
i!=j

tensor([[ True,  True, False],
        [ True,  True,  True]])

#### special functions

In [94]:
k =torch.randint(size=(2,3),low=0,high=10,dtype = torch.float32)
k

tensor([[6., 6., 9.],
        [0., 1., 0.]])

In [91]:
torch.log(k)

tensor([[2.1972,   -inf, 1.9459],
        [1.0986, 0.0000, 0.6931]])

In [92]:
torch.sqrt(k)

tensor([[3.0000, 0.0000, 2.6458],
        [1.7321, 1.0000, 1.4142]])

In [93]:
torch.sigmoid(k)

tensor([[0.9999, 0.5000, 0.9991],
        [0.9526, 0.7311, 0.8808]])

In [97]:
torch.softmax(k,dim=0)

tensor([[9.9753e-01, 9.9331e-01, 9.9988e-01],
        [2.4726e-03, 6.6929e-03, 1.2339e-04]])

In [98]:
torch.relu(k)

tensor([[6., 6., 9.],
        [0., 1., 0.]])

### Inplace Operations

In [99]:
m =torch.rand(2,3)
n = torch.rand(2,3)

print(m)
print(n)

tensor([[0.8102, 0.8767, 0.4744],
        [0.3245, 0.0996, 0.4268]])
tensor([[0.8953, 0.9632, 0.3493],
        [0.5842, 0.2382, 0.4284]])


In [100]:
m.add_(n)

tensor([[1.7054, 1.8399, 0.8237],
        [0.9087, 0.3378, 0.8552]])

In [101]:
m

tensor([[1.7054, 1.8399, 0.8237],
        [0.9087, 0.3378, 0.8552]])

In [102]:
n

tensor([[0.8953, 0.9632, 0.3493],
        [0.5842, 0.2382, 0.4284]])

In [103]:
m.relu_()

tensor([[1.7054, 1.8399, 0.8237],
        [0.9087, 0.3378, 0.8552]])

### Copying a Tensor

In [104]:
a = torch.rand(2,3)
a

tensor([[0.2353, 0.3347, 0.0178],
        [0.5721, 0.7608, 0.6129]])

In [105]:
b =a


In [106]:
a[0][0] = 0

In [107]:
b

tensor([[0.0000, 0.3347, 0.0178],
        [0.5721, 0.7608, 0.6129]])

In [108]:
id(a)

133144254913328

In [109]:
id(b)

133144254913328

In [110]:
b = a.clone()

In [111]:
a[0][0]=1

In [112]:
a

tensor([[1.0000, 0.3347, 0.0178],
        [0.5721, 0.7608, 0.6129]])

In [113]:
b

tensor([[0.0000, 0.3347, 0.0178],
        [0.5721, 0.7608, 0.6129]])

In [114]:
print(id(a))
print(id(b))

133144254913328
133144255392144


### Tensor Operations on GPU

In [3]:
torch.cuda.is_available()

True

In [4]:
device= torch.device('cuda')

In [5]:
#creating a new tensor on GPU
torch.rand((2,3),device=device)

tensor([[0.5466, 0.1582, 0.8187],
        [0.6580, 0.2848, 0.6428]], device='cuda:0')

In [6]:
#moving an existing tensor to GPU
a = torch.rand(2,3)
a

tensor([[0.8780, 0.5048, 0.7347],
        [0.6356, 0.3336, 0.3637]])

In [8]:
b =a.to(device)

In [9]:
b+=5

In [11]:
import time

size = 10000

matrix_cpu1 = torch.randn(size,size)
matrix_cpu2 = torch.randn(size,size)

start_time = time.time()
result_cpu = torch.matmul(matrix_cpu1,matrix_cpu2)
cpu_time = time.time()-start_time

print(f"Time on CPU:{cpu_time:.4f} seconds")


matrix_gpu1 = matrix_cpu1.to('cuda')
matrix_gpu2 = matrix_cpu2.to('cuda')

start_time = time.time()
result_gpu = torch.matmul(matrix_gpu1,matrix_gpu2)
torch.cuda.synchronize()
gpu_time = time.time()-start_time

print(f"Time on GPU:{gpu_time:.4f} seconds")

Time on CPU:15.6579 seconds
Time on GPU:0.5692 seconds


### Reshaping Tensors

In [12]:
a = torch.ones(4,4)
a

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [13]:
a.reshape(2,2,2,2)

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

In [14]:
a.flatten()

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [15]:
b =torch.randn(2,3,4)
b

tensor([[[ 0.4743,  0.0068, -0.4716,  0.7242],
         [ 0.2700, -1.1697, -1.2461, -0.7444],
         [-1.2754,  1.6039, -1.1891, -0.2058]],

        [[-0.5434, -0.9790, -1.1085, -1.7023],
         [-0.8672, -0.9936,  0.0427, -1.2318],
         [ 0.1782, -0.4589, -1.8709, -0.5855]]])

In [16]:
# permute
b.permute(2,1,0).shape

torch.Size([4, 3, 2])

In [23]:
# unsqueeze
c = torch.randn(226,226,3)
c

tensor([[[-2.2046,  1.1900, -0.0386],
         [ 0.8090,  1.8514, -0.3642],
         [-0.8059, -0.0826, -0.4451],
         ...,
         [-0.8368, -1.6221,  0.3834],
         [ 0.2889,  0.5476, -2.1447],
         [ 0.2800,  1.3532, -0.2583]],

        [[ 0.6217,  1.6857, -1.1842],
         [ 0.7782,  1.7920, -0.4698],
         [ 0.8990, -0.1105,  0.7258],
         ...,
         [ 2.0817,  0.4065,  0.0832],
         [ 0.1573,  0.0097,  2.1458],
         [-0.5366,  0.5532, -0.5118]],

        [[-1.2983, -0.1094,  0.4919],
         [ 0.2816, -0.6673, -1.0947],
         [ 1.9053, -0.4069, -0.2843],
         ...,
         [-1.5617, -0.3998,  0.1547],
         [-1.5265, -2.7652,  1.2170],
         [ 0.8723, -0.9498,  0.4130]],

        ...,

        [[ 1.2316, -1.0244,  1.9186],
         [-2.2581, -0.1853, -0.0248],
         [-0.0987,  0.2796,  0.6175],
         ...,
         [ 0.2436, -0.2394,  0.5841],
         [ 0.0580,  0.0354, -1.1334],
         [ 0.5503, -0.0881, -0.8082]],

        [[

In [22]:
#c.unsqueeze(dim=0)

tensor([[[[ 0.7152, -0.3300,  0.3430],
          [ 0.1606,  0.8916,  1.7642],
          [ 0.3073,  0.2016, -0.6496],
          ...,
          [ 1.6063,  0.3092, -0.0514],
          [ 1.0544,  0.7438, -1.1634],
          [ 0.2106,  1.2150,  2.5722]],

         [[ 0.1277, -1.5041, -1.9027],
          [-0.9541, -1.7507,  0.5653],
          [ 0.5208, -0.4270, -0.8484],
          ...,
          [ 0.4369,  1.2476,  0.3724],
          [-1.0675, -1.3806, -1.9007],
          [-0.5038, -0.3636, -1.2173]],

         [[-0.3519,  1.2262,  0.2897],
          [ 1.3111, -1.2655, -0.3548],
          [-0.2621,  0.1380, -1.0358],
          ...,
          [ 1.3037, -0.6917,  0.4260],
          [ 1.3782, -0.8466,  0.9245],
          [-0.3014, -0.5997, -0.4066]],

         ...,

         [[-0.1481, -0.6026,  0.3321],
          [ 0.3160,  0.2634, -0.5822],
          [ 1.3570, -1.7307,  1.9716],
          ...,
          [ 0.7869,  0.8072,  0.2395],
          [-0.9291, -1.0291, -0.9364],
          [ 1.2360, -0

In [24]:
c.unsqueeze(2).shape

torch.Size([226, 226, 1, 3])

In [25]:
#squeeze
d = torch.rand(1,20)
d.squeeze(0).shape

torch.Size([20])

### Numpy and Pytorch

In [26]:
import numpy as np

In [28]:
a=torch.tensor([1,2,3])
a

tensor([1, 2, 3])

In [32]:
b= a.numpy()
b

array([1, 2, 3])

In [33]:
type(b)

numpy.ndarray

In [34]:
c = np.array([1,2,3])
c

array([1, 2, 3])

In [35]:
torch.from_numpy(c)

tensor([1, 2, 3])